language: python
sudo: true
dist: trusty

# The Travis build will test OSX distributions ONLY, and the language
# needs to be overridden to "generic" for Mac, otherwise the build will fail
# until Python is downloaded via Homebrew (which is handled in the
# before_install.sh). All artifacts are 64-bit ONLY.

matrix:
  include:
    - language: generic
      os: osx
      python: 3.5.6
      osx_image: xcode9.3
      env: PYTHON="3" OPENBLAS_NUM_THREADS="1" DEPLOY="true"

    - language: generic
      os: osx
      python: 3.6.6
      osx_image: xcode9.3
      env: PYTHON="3" OPENBLAS_NUM_THREADS="1" DEPLOY="true"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

before_install: source build_tools/travis/before_install.sh
install: source build_tools/travis/install.sh
script: bash build_tools/travis/test_script.sh

cache:
  - apt
  - directories:
    - $HOME/.cache/pip

# we set +e to re-instate the error-tolerant state. The problem is Travis is broken on Mac OS
# builds right now due to Issue 6307 (https://github.com/travis-ci/travis-ci/issues/6307)
# and fails at the end of a successful build. This will allow the build to recover even if
# a non-zero status code is encountered. (had `- set +e`)
after_success:
  - source build_tools/travis/after_success.sh
  # Build the wheels every time so we can debug
  - bash build_tools/travis/build_wheels.sh
  - ls dist/

deploy:
  provider: script
  skip_cleanup: true
  script: python -m twine upload --skip-existing dist/*.whl
  on:
    tags: true # Upload on tagged releases
    condition: "$DEPLOY = true"
